### ISSUE TITLE
[Meta] Deletion of TPRs via catalog API Server fails

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#600] opened 2017-03-22 17:18 UTC
_Note: this issue is made up of several smaller ones. Ideally a single patch should close this and all of the smaller ones. See https://github.com/kubernetes-incubator/service-catalog/issues/600#issuecomment-300330144 for details._

Upon trying to run `kubectl delete -n test-ns bindings ups-binding` as per the walkthrough, I get:

```
The ThirdPartyResourceData "ups-binding" is invalid: 
* metadata.deletionGracePeriodSeconds: Invalid value: 0: field is immutable; may only be changed via deletion
* metadata.deletionTimestamp: Invalid value: "2017-03-21T20:20:05Z": field is immutable; may only be changed via deletion
```

API server logs: http://pastebin.com/5BFFMsuv
Catalog logs: http://pastebin.com/VTZPP5rz

**Comment by arschles** [comment] 2017-03-22 20:12
@kibbles-n-bytes the workaround is to delete the TPRs directly on kubernetes core. you could use that workaround on https://github.com/kubernetes-incubator/service-catalog/pull/602, but obviously it won't close this issue

**Comment by arschles** [comment] 2017-03-22 20:15
may be fixed by work that comes out of https://github.com/kubernetes-incubator/service-catalog/issues/599

cc/ @krancour

**Comment by krancour** [comment] 2017-04-03 18:13
@arschles #612 (which is meant to close #599) _also_ seems to have this problem.

**Comment by arschles** [comment] 2017-04-03 18:38
@krancour good to know, thanks

**Comment by arschles** [comment] 2017-04-13 16:32
cc/ @simonleung8

**Comment by arschles** [comment] 2017-04-13 19:25
@simonleung8 is currently working on this. I am moving this into 0.0.4

**Comment by simonleung8** [comment] 2017-04-19 23:00
A workaround has been posted to resolve this issue. see #718

**Comment by simonleung8** [comment] 2017-04-20 05:44
PR #718 is open as an workaround to get the walk through working.

**Comment by simonleung8** [comment] 2017-04-20 05:45
I have to close the PR because it is breaking integration test for etcd. Will further investigate to find a proper remedy.

**Comment by arschles** [comment] 2017-04-21 18:36
Moving to the beta cycle, as this is still in progress

**Comment by krancour** [comment] 2017-04-27 22:20
https://github.com/kubernetes-incubator/service-catalog/pull/738 just recently fixed the update for tpr-backed storage. I'm not 100% of the root cause behind _this_ issue, but delete via apiserver is a soft-delete-- which is really an update. I _suspect_ that this issue can be closed, but I really need to try the walkthrough using the new and improved (and better tested) tpr storage. I will try and get that done tomorrow if not sooner.

**Comment by arschles** [comment] 2017-05-09 21:48
I confirm that this is still an issue on the `canary` as of right now. The logs that are returned on the API server are as follows:

```console
I0509 21:46:23.684728       1 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ThirdPartyResourceData.extensions \"ups-broker\" is invalid: [metadata.deletionGracePeriodSeconds: Invalid value: 0: field is immutable; may only be changed via deletion, metadata.deletionTimestamp: Invalid value: 2017-05-09 21:46:23 +0000 UTC: field is immutable; may only be changed via deletion]","reason":"Invalid","details":{"name":"ups-broker","group":"extensions","kind":"ThirdPartyResourceData","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: 0: field is immutable; may only be changed via deletion","field":"metadata.deletionGracePeriodSeconds"},{"reason":"FieldValueInvalid","message":"Invalid value: 2017-05-09 21:46:23 +0000 UTC: field is immutable; may only be changed via deletion","field":"metadata.deletionTimestamp"},{"reason":"FieldValueInvalid","message":"Invalid value: 0: field is immutable; may only be changed via deletion","field":"metadata.deletionGracePeriodSeconds"},{"reason":"FieldValueInvalid","message":"Invalidvalue: 2017-05-09 21:46:23 +0000 UTC: field is immutable; may only be changed via deletion","field":"metadata.deletionTimestamp"}]},"code":422}
E0509 21:46:23.685068       1 storage_interface.go:556] executing PUT to servicecatalog/ups-broker (ThirdPartyResourceData.extensions "ups-broker" is invalid: [metadata.deletionGracePeriodSeconds: Invalid value: 0: field is immutable; may only be changed via deletion, metadata.deletionTimestamp: Invalid value: 2017-05-09 21:46:23 +0000 UTC: field is immutable; may only be changed via deletion])
```

It looks like this is related to not setting the resource version properly (#723)

**Comment by simonleung8** [comment] 2017-05-09 22:02
@arschles The rewrite from @krancour seems to have fixed the issue, I can successfully delete TPR resource going through our walk through with the canary build. Your failure might be due to another issue.

With v0.04
```
$ kubectl --context=service-catalog delete -n test-ns bindings ups-binding
The ThirdPartyResourceData "ups-binding" is invalid:
* metadata.deletionGracePeriodSeconds: Invalid value: 0: field is immutable; may only be changed via deletion
* metadata.deletionTimestamp: Invalid value: "2017-05-09T21:57:07Z": field is immutable; may only be changed via deletion
```

With canary
```
$ kubectl --context=service-catalog delete -n test-ns bindings ups-binding
binding "ups-binding" deleted
```

**Comment by arschles** [comment] 2017-05-09 23:27
I've changed the title of this issue to include `[Meta]`, because there are several other issues that describe sub-problems of this one:

- #720: since delete uses `GuaranteedUpdate` to do soft-deletes, that function needs to be fixed
- #732: we'll likely need to change resource version handling to make `GuaranteedUpdate` work properly

**Comment by arschles** [comment] 2017-05-10 15:45
Moving to 0.1.0 as this has not been completed

**Comment by arschles** [comment] 2017-05-11 18:42
The issue is as follows:

When the API registry gets a `DELETE`, it sets the deletion timestamp and deletion grace period on the resource and calls `GuaranteedUpdate`. The TPR storage implementation fails because it tries to `PUT` those changes on the upstream API, but those fields are read-only. 

My proposed solution is to try intercepting calls to update those fields in `GuaranteedUpdate` and set a finalizer on the TPR instead.

**Comment by arschles** [comment] 2017-05-17 22:29
Moving to 0.1.0, as #836 is not yet finished

**Closed** 2017-05-24 16:39 UTC
Labels: bug, third-party-resources
