### ISSUE TITLE
Add support for Pod-Preset - aka Pod Injection Policy

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#266] opened 2017-01-16 21:03 UTC
Just a spot for pointers to the real work so its easy for people to find the other issues, PRs and design docs.

k8s/features issue:  https://github.com/kubernetes/features/issues/162
k8s/community PR: https://github.com/kubernetes/community/pull/254
k8s/kubernetes PR: https://github.com/kubernetes/kubernetes/pull/41931

**Comment by pmorie** [comment] 2017-03-01 19:34
I think we should move this to the MVP 2 milestone.  The resource will be in Kubernetes 1.6, so we should be able to implement this once we do #413.  Thoughts?

**Comment by duglin** [comment] 2017-03-01 19:48
the title of the milestone doesn't matter as much to me - I'm more interested in us hooking it up as soon as we rebase on kube 1.6 - and I'd like that sooner rather than later.

**Comment by pmorie** [comment] 2017-03-01 19:50
@duglin 

> I'm more interested in us hooking it up as soon as we rebase on kube 1.6 - and I'd like that sooner rather than later.

Yep, we're in 100% agreement about that.  That will be in mvp-2.

**Comment by arschles** [comment] 2017-03-01 19:51
We have all talked about this before, so I'll repeat here - I'd like support for pod-presets to be built completely behind a feature flag.

**Comment by arschles** [comment] 2017-03-13 18:07
This will be done with #413

**Comment by arschles** [comment] 2017-03-13 18:10
Assigned to you @pmorie since you'll complete this with #413

**Comment by arschles** [comment] 2017-04-13 18:46
This is a duplicate of #637. Closing

**Comment by pmorie** [comment] 2017-05-10 23:06
Re-opened because this is the original issue.

**Comment by pmorie** [comment] 2017-05-10 23:06
After doing some exploration in #670, I have found an issue that means we will have to rethink the first version of this integration (ie, the first alpha integration that we do at this moment) because of a snag that I hit once I begin plumbing through the `PodPresetSpec` field in the API.

The fundamental issue is that there is no good way to validate an API type from a core API group (except for the metav1 group, which exports validations) outside the core API server.  No versioned validations are exported.  You cannot even do something like vendoring the kube code and converting to the internal format, because the package that we consume the API types from is transformed when `client-go` is exported from the main kubernetes repo.  I opened https://github.com/kubernetes/kubernetes/issues/44995 to try to solve this problem, but after some thought, I do not think exporting code for validations is the right thing.  I have some ideas about the right solution, but I will keep the discussion of those on the linked issue.

Long-term, we need to be able to validate API types like this outside the core API server.  Once we can do that, we can easily just embed a `PodPresetTemplateSpec` in our API surface and validate it all over town.

However, for now, there is not a good way to integrate the `PodPresetSpec` type itself into our API surface.  I have a strong desire and business need to be able to leverage pod preset ASAP in our API, so I have been thinking about stopgap measures.  One fairly easy stop gap is to add support only for the new `envFrom` feature that is present in kubernetes 1.6.  Given a name for a pod preset and a label selector for that pod preset in our API, we could generate a pod preset that would add a new `envFrom` for the secret referenced in the binding.  

Here's a sketch of what that would look like in our API:

```go
type BindingSpec struct {
	// other fields omitted

	AlphaPodPresetName *string
	AlphaPodPresetLabelSelector *metav1.LabelSelector
}
```

We can validate `LabelSelector` type with an exported validation from the `metav1` group, and of course, the name is easy to validate with a ton of leakage of information into our validation code (it's the same as the validation for secret name, which we already do).

So, for an example, given the following binding:

```yaml
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
metadata:
  name: test-binding
  namespace: test-ns
spec:
  instanceRef:
    name: test-instance
  secretName: my-secret
  alphaPodPresetName: my-pod-preset
  alphaPodPresetLabelSelector: 
    matchLabels:
      app: frontend
```

We would produce a `PodPreset` like so:

```yaml
kind: PodPreset
apiVersion: settings.k8s.io/v1alpha1
metadata:
  name: my-pod-preset
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: frontend
  envFrom:
    - secretRef:
        name: my-secret
```

This would at least be usable to give us coverage of an 80% (or 80% of 80%) use-case, and I think would be very usable to people.  I would also be fine with plumbing through a prefix field for the `EnvFrom` if people need that.

**Comment by pmorie** [comment] 2017-05-10 23:50
Set the milestone to 1.0.0 for now, because this isn't going to be done before 0.1.0 and it doesn't need to be (since the fields will inherently themselves be alpha).  I hope to get to this perhaps in 0.1.1

**Comment by duglin** [comment] 2017-05-11 00:03
I think adding a mechanism to get to the secret values w/o calling the kube API is a must. I don't want to have to turn all of my apps that use services into kube clients.

**Comment by MHBauer** [comment] 2017-05-11 00:13
My understanding of what you are saying:
 - We can't validate the type before it gets stored
 - we can't use the upstream code because it operates on different objects
 - we don't want to copy the validation because maintenance
 - instead of taking a full podpreset, take a name and some subfields and generate one ourselves to support setting environment variables (and thus, not mounts?) 

Can we just, not validate and fail later? What does that look like from an operational perspective? Where does the error happen if it's a bad spec?

`the package that we consume the API types from is transformed when client-go is exported from the main kubernetes repo.`
They should stop doing that. Everybody should use the same thing and be on the same level.


`name is easy to validate with a ton of leakage of information into our validation code (it's the same as the validation for secret name, which we already do`
What is this leakage?

This would seem to be a blocker for a beta of the API, or it necessitates a V2 whenever the validation is actually added.

**Comment by pmorie** [comment] 2017-05-11 02:34
> My understanding of what you are saying:
 
What you wrote is correct.

> Can we just, not validate and fail later? What does that look like from an operational perspective? Where does the error happen if it's a bad spec?

I assume you're wondering about if we were to use `PodPresetSpec` in our API, but not validate at Binding creation time.  I considered this, but I don't think it's the right thing.  Thinking through that possibility:

1.  You make a binding that has an invalid PodPresetSpec
2.  The service catalog API server accepts the Binding, and does not give you a validation error at creation time
3.  Your expectation after (2) will be from using Kubernetes that everything should be good
4.  Later, the controller does a binding on behalf of you, and then fails when it tries to create a `PodPreset`
5.  Now you're stuck - we errored after a binding was already made, and your best bet would be to delete and recreate the binding

This is not the kind of experience I want to have as a k8s user.  In general, our users expect that these kinds of validation errors surface when the resource is created.  So, letting the validation error happen at runtime is not a good experience.

>> name is easy to validate with a ton of leakage of information into our validation code (it's the same as the validation for secret name, which we already do
>
> What is this leakage?

I mean that we can validate the name of a PodPreset easily without pulling in and mutating validation code from the core.

> This would seem to be a blocker for a beta of the API, or it necessitates a V2 whenever the validation is actually added.

It is not, because PodPreset-related fields in out API are necessarily going to be alpha until the resource itself is at beyond alpha.  So, this does not block our API moving to beta, it only blocks the fields related to PodPreset moving beyond alpha.

**Comment by pmorie** [comment] 2017-05-11 04:45
cc @jwforres @spadgett

**Comment by bklau** [comment] 2017-05-18 20:48
3 questions:
1. Does one need to deploy the  pods first before applying a pod preset that selects them?
2. So the pods that got selected for preset injection is restarted?.  If so, seems like a waste of lifecycles.
3. If a  pod preset is deleted while the injected pods are still running, what  happens to them?

**Comment by duglin** [comment] 2017-05-19 06:25
@bklau 
1 - normally the podpreset is created first since it will only act on pods created **after** the podpreset is known
2 - nope, only new pods are modified. So the user would need to specifically ask for their app/pods to be redeployed
3 - nothing, same as pods that are created before the podpreset is created.  Creating a podpreset does not touch currently running pods.

**Comment by bklau** [comment] 2017-05-19 20:24
@duglin  : Thx for the explanations : ) . Which release will the service catalog be in?

**Comment by duglin** [comment] 2017-05-23 12:21
podpreset is already in Kube v1.6, so that dependencies is fulfilled. Not sure when svc-cat will be part of an official release, but since it pretty much is stand-alone and doesn't require any more changes in the core you should be able to use it today.  Currently, its in alpha, we're hoping to go to "beta" very soon (like within a week or so).

**Closed** 2017-06-09 00:39 UTC
Labels: api
