### ISSUE TITLE
SelfLink for Brokers is incorrect

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#309] opened 2017-01-26 21:03 UTC
It currently includes `namespaces`, which is incorrect, because Broker is a non-namespaced resource:

```yaml
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  creationTimestamp: 2017-01-25T21:34:23Z
  name: test-broker
  resourceVersion: "4"
  selfLink: /apis/servicecatalog.k8s.io/v1alpha1/namespaces//brokers/test-broker
  uid: 0a1f62e1-e346-11e6-99ac-68f728db1985
```

It should be:

```yaml
  selfLink: /apis/servicecatalog.k8s.io/v1alpha1/brokers/test-broker
```

**Comment by MHBauer** [comment] 2017-02-18 04:55
Links so we don't lose them:
https://github.com/kubernetes/kubernetes/issues/37622
https://github.com/kubernetes/kubernetes/pull/41011

This concerns me because it somehow implies that all of the core stuff is hardcoded to work.

**Comment by arschles** [comment] 2017-03-13 18:14
Will be fixed by #413. @pmorie assigned to you since you + others will be doing that issue

**Comment by arschles** [comment] 2017-04-03 19:02
I've moved this to `0.0.2`, as this will be fixed by fixed by the rebase in #413

**Comment by pmorie** [comment] 2017-04-07 17:33
Current state: still incorrect, but closer:

```yaml
  selfLink: /apis/servicecatalog.k8s.io/v1alpha1/brokersups-broker
```

**Comment by pmorie** [comment] 2017-04-07 17:33
Moving this to 0.0.3, because it doesn't look like this will be done in time.

**Comment by DirectXMan12** [comment] 2017-04-07 17:57
yep, totally looks like just a bug in generic API server.  Seems to affect nodes and namespaces as well.  The problem is that the path "/" is effectively the empty path when used not at the beginning of a path, so `path.Join(a.prefix, resourcePath, "/") == path.Join(a.prefix, resourcePath)` (the relevant code is here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L397). 

The important bits of the path library can be found here:

https://golang.org/pkg/path/#Clean
> The returned path ends in a slash only if it is the root "/". 

https://golang.org/pkg/path/#Join
> The result is Cleaned

**Comment by arschles** [comment] 2017-04-13 18:45
I am moving this into 0.1.0 since we it would be nice to have this fixed once we start providing backward-compatibility guarantees to our data types at that time.

**Comment by MHBauer** [comment] 2017-05-22 17:43
looking through e2e results, I see some of the responses have `{name}` in them for the selflinks. Is something need to interpolate client side that is not being done, or something that should be done server side before sending the response?

**Comment by DirectXMan12** [comment] 2017-06-14 17:42
the selflinks should not require any interpolation client-side.  If you're still seeing that, it's probably a bug.

**Comment by MHBauer** [comment] 2017-07-24 22:55
All selflinks appear to be working correctly now.

**Closed by MHBauer** 2017-07-24 22:55 UTC
Labels: api, bug
