### ISSUE TITLE
Rename Binding to avoid collision with native k8s resource

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/service-catalog#1008] opened 2017-07-06 21:14 UTC
Kubernetes has a core resource called `Binding` that was used by the scheduler.

it was deprecated in k8s 1.7, but it will remain for a period of time.

see: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L3217

if i use service-catalog integrated with a api server aggregation, i find our kubectl clients get confused when calling `kubectl get bindings` as it selects the core Binding resource, and not the catalog one.

I think we should potentially rename `Binding` to `ServiceBinding` as a result.

**Comment by derekwaynecarr** [comment] 2017-07-06 21:14
fyi @pmorie @jwforres @smarterclayton - per our discussion.

**Comment by duglin** [comment] 2017-07-06 21:21
bummer. We may want to consider prefixing all of our resources with the same name (e.g. `Service`) so we have some consistency.

**Comment by derekwaynecarr** [comment] 2017-07-06 21:22
@duglin - yes, i have had similar feedback re: `Instance` -> `ServiceInstance`

**Comment by MHBauer** [comment] 2017-07-06 21:28
```
if i use service-catalog integrated with a api server aggregation, i find our kubectl clients get confused when calling kubectl get bindings as it selects the core Binding resource, and not the catalog one.
```
Pretty sure I've seen this, not that I knew what it was.

Irritating that we end up doing a lookup by Kind when we really want specifically the Kind in a specific group. Is there anyway to add some reference to kubectl commands to get what we want? `kubectl get po/xyz` to get pod xyz, can we extend kubectl or some such to be `kubectl get svccat/binding/xyz` ?  This seems like there is a large potential for installed and aggregated apiresources to have collisions in the future and not even know that they are having the problem.

Can I get a warning from kubectl that this is an ambiguous ask? 

We are going over all of the names in #638.

**Comment by duglin** [comment] 2017-07-13 02:30
Proposal:  Rename our resources to be:
```
ServiceBroker
ServiceBrokerList
ServiceBrokerSpec
ServiceBrokerAuthInfo
ServiceBrokerStatus
ServiceBrokerCondition
ServiceInstanceList
ServiceInstance
ServiceInstanceSpec
ServiceInstanceStatus
SevrviceInstanceCondition
ServiceBindingList
ServiceBinding
ServiceBindingSpec
ServiceBindingStatus
ServiceBindingCondition
```

Unchanged:
```
ServiceClassList
ServiceClass
ServicePlan
```

For discussion on tomorrow's design call.

**Comment by nilebox** [comment] 2017-07-13 21:15
> We may want to consider prefixing all of our resources with the same name (e.g. Service) so we have some consistency.

if not `ServiceCatalog*`...

**Comment by duglin** [comment] 2017-07-13 21:46
On today's design call there was general agreement that we should try to see if we can come up with a common prefix for all of our resources. While whatever we pick might not pass review with the Kube API group, we'd like to start with that as our initial proposal.  We decided to continue our bikeshedding on the exact prefix to use in Slack.

@MHBauer pointed out that this is part of a bigger issue and should be something that's address at a more global level.  But in the meantime we need a solution that will work for the current state of things.

**Comment by duglin** [comment] 2017-07-14 17:21
per @pmorie's request, I'm moving #1033 into here - while not the exact same issue they're closely related:

If we decide to remove PodPreset from Binding, the Binding resource no longer relates to the action of "binding" an app to a service instance. What it becomes is more akin to what CF calls a ServiceKey.

This name change is good for a variety of reasons:

    we've been overlooking an important usecase: a kube client asking for the credentials of a service instance w/o asking kube to bind it to an app. This renaming helps with that by allowing people to ask for exactly what they want (the creds) w/o being confused by an unnecessary term like "binding".
    as we've been discussing, there will be lots of ways that people will want to "bind" or just "use" the creds from the service broker. In that vein, I think "binding" is too limiting a term, or more bluntly an incorrect term, at this point in the UX flow.
    If we do add some nice UX resources (like PodPresetBinding) I think putting the word "Binding" on those is more appropriate and more accurately describes what's going on.

So the overall flow would look like:

$ kubectl create -f svcInstance.yaml    # create mongoDB
$ kubectl create -f svcKey.yaml         # create a key/secret for the creds
$ kubectl create -f podpreset.yaml      # "bind" the key to my app
$ kubectl create -f myapp.yaml          # now deploy the app

Having the word/resource "Binding" at the 2nd step could be misleading and confusing to people.

Note that once we decide on our prefix this might become something like "ServiceCatalogKey".

**Comment by nilebox** [comment] 2017-07-16 23:24
> the Binding resource no longer relates to the action of "binding" an app to a service instance

> w/o being confused by an unnecessary term like "binding".

I agree that "binding" resource name is confusing, but on the other hand this term was not invented by us. This is what credentials request is called in OSB. And without renaming Binding to ServiceKey in OSB spec, I am afraid this change could be even more confusing.

**Comment by duglin** [comment] 2017-07-17 02:28
I don't see a name change happening in the spec until v3.  However, on the potential of using ServiceKey in the platform, CF does it today w/o any concern or confusion.

**Comment by nilebox** [comment] 2017-07-17 03:15
@duglin what do you think of `InstanceAccessKey` (potentially ServiceCatalogInstanceAccessKey in the future...) instead of `ServiceKey`?
`ServiceKey` sounds ambiguous to me. I would prefer having `Instance` as part of the new name, if we go for the change.

**Comment by duglin** [comment] 2017-07-17 03:18
If CF didn't set the precedent for it being called "Service-Key" then I'd be ok with it. So, for consistency sake I'm still leaning towards ServiceKey but if the group wants to use InstanceAccessKey I can live with it - either is better than Binding :-)

**Comment by nilebox** [comment] 2017-07-17 03:36
FWIW as mentioned before in other discussions, CF was not concerned about the UX of internal platform features (by design), while in Kubernetes (and Service Catalog) world with user-facing API it's a bit different. So I wouldn't consider compatibility with internal CF naming as a major goal for svc-cat, if there is an alternative approach with better UX.

**Comment by wjiangjay** [comment] 2017-07-18 09:00
Just note here, all related **roles** for authorization should be updated too after this issue.

**Comment by duglin** [comment] 2017-07-18 16:19
on yesterday's call we agreed to use "ServiceCatalog" as the prefix.  PR needed.

**Comment by duglin** [comment] 2017-07-18 18:43
#dibs

**Comment by duglin** [comment] 2017-07-18 20:33
we agreed to ServiceCatalogInstanceCredential on today's design call

**Comment by pmorie** [comment] 2017-07-19 05:28
@duglin does [this message](https://github.com/kubernetes-incubator/service-catalog/issues/1008#issuecomment-316159736) indicate your intent to make the code change, or something else?

**Comment by pmorie** [comment] 2017-07-19 05:31
The more I think about it, the more I like this name, especially when thinking about creating an `InstanceCredential` in the same helm chart / template / yaml file as a `PodPresetBinding` or a `VCAPServicesBinding` and/or an `IstioRuleBinding`, etc.

"Credentials are 'bound'" to apps also seems to make sense for an explanation.

**Comment by nilebox** [comment] 2017-07-19 05:33
> we agreed to ServiceCatalogInstanceCredential on today's design call

singular "Credential" sounds a bit weird for me (as opposed to Credentials), but I guess the Kubernetes resource name must be singular, right?

**Comment by pmorie** [comment] 2017-07-19 05:38
They're generally singular, but remember that in the CLI, they're pluralized ie:  `kubectl get servicecatalogbrokers`

**Comment by nilebox** [comment] 2017-07-19 06:06
FWIW I never use plurals in kubectl, it works for singular too:
```
❯ kubectl get pod --all-namespaces
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
kube-system   default-http-backend-zjcxn       1/1       Running   0          8m
```

**Comment by duglin** [comment] 2017-07-20 00:53
@pmorie yea the #dibs and me assigning it to myself.

**Comment by pmorie** [comment] 2017-07-31 15:19
Closing; we will make #1080 the issue to record all discussion of API resource naming going forward.

**Closed by pmorie** 2017-07-31 15:19 UTC
