### ISSUE TITLE
Standardize location for all Jenkins-related scripts

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#143] opened 2016-12-08 19:35 UTC
After https://github.com/kubernetes-incubator/service-catalog/pull/139 and similar PRs, jenkins scripts are "all over the place". This issue is for standardizing a location for them and making the change to move them to the right directory.

**Comment by pmorie** [comment] 2017-01-11 22:56
Duplicate of #137

**Closed by pmorie** 2017-01-11 22:56 UTC
Labels: enhancement, testing
