### ISSUE TITLE
Global and NS-specific Brokers, Classes and Plan

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#1233] opened 2017-09-17 19:35 UTC
Right now brokers, classes and plans are global, meaning they are cluster-wide and are not scoped to a particular namespace.  There are going to be times when people will want things localized to a namespace. We need to consider how we'll support these.

Some notes:
- Global Broker/NS Classes : may not be a visibility issue, rather its an RBAC/ACL issue.  Meaning, we may not be able to hide these classes from people in other namespaces, but we should be able to block their ability to use them via some policy mechanism.  For example, define a "policy" resource that defines who has what access to the Class, or add data to the class itself to represent this info. Then use an admin controller to allow/block usage.
- NS Broker : would be visible to just the NS. We may need to create new resources (e.g. LocalServiceBroker/Class/Plan) since current resources are non-NS scoped.
- Global Instances : how do we deal with instances that are not scoped to a namespace?

marking this a v0.1.0 since I think we need to discuss and make sure we don't need changes before beta.  Of the ones listed above I think the "Global Instances" one might need to be addressed before beta because if we prepend the word "Local" to Broker/Class/Plan to indicate they're NS-specific, then perhaps our current ServiceInstance should be LocalServiceInstance too?

**Comment by duglin** [comment] 2017-09-17 19:42
If we do support global instances I wonder how we'll create bindings/creds.  I believe that secrets are bound to namespaces, so that might mean that to get the creds for a global instance we'd need to bind it to a namespace. While that may be necessary from an ACL perspective in Kube, it seems to defeat the purpose of a "global" instance.  Although, having a "global" resource could mean that you're doing admin (cluster-wide) type of stuff anyway, so perhaps there won't be the notion of bindings/creds at all for these types of services. The ACL side of it will be done via the OriginatingIdentity header on the provision request.  Just wondering....

**Comment by pmorie** [comment] 2017-09-17 20:10
Dupe of https://github.com/kubernetes-incubator/service-catalog/issues/1200

Can you add these notes there and close?

**Closed** 2017-09-18 01:35 UTC
