### ISSUE TITLE
Change what we send for org, space and context

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#800] opened 2017-05-05 17:07 UTC
We're in a situation where we have multiple clusters all talking to the same brokers and we need a way to be able to distinguish between those clusters in the SB API calls.  Since right now we don't really use org and space much, we just populate them with the namespaceUID to have something in there, I'd like to propose we do this:

- set orgID to the kube cluster ID
- set spaceID to the namespace UID (no change)
- add a "clusterID": "...." property to the new "context" parameter.

I'll be proposing the "context" change to the OSB API spec later today.

This should allow for brokers who toss out extra noise in the messages (like "context") to still have access to the clusterID and namespace via the org and space fields.

**Comment by simonleung8** [comment] 2017-05-05 17:11
#dibs

**Comment by pmorie** [comment] 2017-05-05 17:20
What is the form of the 'cluster id', and where does it come from?

**Comment by duglin** [comment] 2017-05-05 17:53
no idea yet :-)   that's part of what simon was going to investigate.  Any pointers on where to get that from? I seem to recall you mentioning cluster id in the past.

**Comment by pmorie** [comment] 2017-05-05 18:24
I agree we need to figure out what these fields mean to us and how to give
a cluster a unique id. Ine thing we could pass is the endpoint for the API
server (we need to do this anyway for brokers that need to talk back to the
k8s API server), but that could also change over time (say your dns name
changes or you start/stop using a VIP for some reason).

So, basically, I don't know for sure yet, but I am motivated to get
something figured out.

**Comment by duglin** [comment] 2017-05-05 20:36
I'm thinking the UID of the cluster that I see from  `kubectl cluster-info dump` might work:
```
{
    "selfLink": "/api/v1/nodes",
    "resourceVersion": "4173",
    "Items": [
        {
            "name": "127.0.0.1",
            "selfLink": "/api/v1/nodes127.0.0.1",
            "uid": "2b4bb06f-31c1-11e7-86e9-000c2946f14f",
...
```
Thoughts?

**Comment by duglin** [comment] 2017-05-05 20:38
oh wait, that's node info (I think)... never mind

**Comment by pmorie** [comment] 2017-05-05 21:15
Yeah, that's the node info.

**Comment by pmorie** [comment] 2017-05-05 21:17
Btw, this is a dupe of https://github.com/kubernetes-incubator/service-catalog/issues/583, so we should move the discussion over there.

**Comment by duglin** [comment] 2017-05-05 23:29
One idea, for cluster-id, see https://github.com/kubernetes/kubernetes/issues/19831 .
Since this isn't implemented yet we could just create a configmap ourselves and generate a cluster-id into it. When/if the core feature is implemented we could switch over.

**Comment by duglin** [comment] 2017-05-08 18:12
More notes...
See https://github.com/kubernetes/kubernetes/blob/master/pkg/master/controller.go#L144  and in particular https://github.com/kubernetes/kubernetes/blob/master/pkg/master/controller.go#L139 for kube's version of an init() function and how it deals with the default namespace.  Similar logic could be done for a ClusterConfig configMap (that has a "ClusterID" property)

We may be able to use federation's notion of a clusterID... still investigating....

**Comment by duglin** [comment] 2017-05-08 21:10
There's this field from the federation work:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L216
But I don't think this will work for us since this is set by the federation control plane and since its on each resource, not at the cluster level, there's really no way for a cluster to know its name w/o asking the federation control plane.

**Comment by arschles** [comment] 2017-05-08 21:14
We discussed in the SIG call today what each of these values means in CloudFoundry, and likely means in production clusters.

My only comment at this time is about `org`. This value is at the top of the "hierarchy" of these values, and as we discussed, it's most likely used for billing. The user (the person who creates new `Instance`s) should not be able to set it.

Instead, we should store this value somewhere that is user-accessible. We proposed these options in the meeting:

1. Store it in an annotation on `Namespace`
2. Pass it in as a CLI flag to the controller

We decided that (2) is only to be used if we exhaust all other options. Thinking further about this, I don't think we should pursue it. If I understand it correctly, it effectively would make `org` static for an entire cluster, which is not practical.

I'll propose another solution (in addition to the `Namespace` annotation): adding another namespaced resource to the API that identifies these values. Operators can use RBAC to close write access to this resource for users of the namespace.

**Comment by duglin** [comment] 2017-05-08 21:18
What is the equivalent of "the billing entity" in Kube? I tend to think of it as the namespace but perhaps its "service account". What do other's think?  That might influence the answer.

**Comment by duglin** [comment] 2017-05-09 00:53
After some investigation I don't think the ClusterName from the federation stuff will help. First, its only on when federation support is there, and there's no way for a cluster to find out its value w/o talking to the federation control plane - again, only when fed is on.

So, @simonleung8 and I were talking and we'd like to propose this plan:
- Follow in the path of the "default namespace" idea ( https://github.com/kubernetes/kubernetes/blob/master/pkg/master/controller.go#L117 ) and during Controller.Start() create a "ClusterConfig" configMap resource
- Populate it with a "clusterID" property. Its value will be a random GUID.
- We'll need to do the same thing as the "default namespace" and periodically check to make sure no one deleted it by mistake - if they do, recreate it. Unless there's a mechanism in Kube to block a delete on it???  Note, if we have to recreate it then it'll get a new random GUID.
- I'm not suggesting we do anything special w.r.t. kubectl - meaning while the configMap is in the system its basically hidden data for internal use.  We can look at @philips `kubectl cluster-info` type of suggestion (https://github.com/kubernetes/kubernetes/issues/19831#issuecomment-183095014 ) at a later time.
- I'd like to get this into v1.7 - would this be considered a "feature" or just a value-add PR ?


This will give us a cluster-wide, static, value that we can then use in the svc-cat messages - as well as work for @philips comment

Thoughts?

**Comment by duglin** [comment] 2017-05-11 02:07
Based on today's call, there was general agreement to implement the CluserConfig configMap and use the clusterID as the orgGUID. We can then use the namespace UID as the spaceGUID and see https://github.com/kubernetes-incubator/service-catalog/issues/798 for what to do about the app_guid.

As for the context, we can put the clusterID in there as new field. We'd need to update the "context profile" doc to include it.

On a side note, we may need to allow users to override these values on a per Broker basis, or globally, but that can be discussed later since we don't have any concrete need for it yet.

**Comment by arschles** [comment] 2017-05-15 16:37
Since this doesn't touch our API surface, I am moving this out of 0.1.0 and into 1.0.0

**Comment by simonleung8** [comment] 2017-05-24 23:16
A PR has been made to add cluster-id to core controller
https://github.com/kubernetes/kubernetes/pull/46384

**Comment by duglin** [comment] 2017-07-10 00:59
Moving this to v0.2.0 instead of v1.0.0 because I want to get this in sooner rather than later - and if something comes up that makes it so we can't do what our current plans are then we'll need something else and that might take time - which could put 1.0.0 into a holding pattern - which I'd like to avoid.

**Comment by MHBauer** [comment] 2017-09-01 21:21
With the 1.8 code freeze, I don't think we're getting any upstream resolution in time for beta. 

I think we should proceed with one of the automatic choices we've discussed as well as let the user set the ID as a flag on our apiserver.

**Comment by duglin** [comment] 2017-09-01 21:29
We don't need to rush this decision, but if upstream changes are not ready any time soon then we should just create our own clusterID within the svc-cat apiserver (using the same logic that we proposed for core) and use that.  We can't wait on the bike-shedding of the core team forever.

**Comment by MHBauer** [comment] 2018-01-10 18:19
[options summary document ](https://docs.google.com/document/d/1bAqjqQTo7F0off7Did1_XNbXEY_mHbPmeXDDSOuWkNA)

[configmap specific proposal document](https://docs.google.com/document/d/1pwC1VDbnsIJmgfoZIMc4yMmxSLS4QflBNhL89OmLJ-g)

configmap implementation in #1658

**Comment by MHBauer** [comment] 2018-03-29 23:01
@duglin https://github.com/kubernetes-incubator/service-catalog/pull/1658 does most of this, do we still want to send cluster id as the CF org?

**Comment by duglin** [comment] 2018-03-30 00:37
@arschles do you have any objection to using ClusterID as the orgID?

**Comment by MHBauer** [comment] 2018-06-07 23:13
@duglin @arschles 
Here is where we send ID in context: https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.21/pkg/controller/controller_instance.go#L1500
This is where we would need to set the orgID: https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.21/pkg/controller/controller_instance.go#L1519

**Closed** 2018-07-02 20:43 UTC
Labels: assigned, broker-api-spec-alpha, broker-api-spec-compliance
