### ISSUE TITLE
service catalog should send user identity to broker

### ISSUE THREAD

**Issue by jim-minter** [kubernetes-incubator/service-catalog#934] opened 2017-06-12 15:59 UTC
See https://github.com/openservicebrokerapi/servicebroker/pull/222

If my suggestion https://github.com/openservicebrokerapi/servicebroker/pull/222#issuecomment-307812990 were to be followed, this might mean the service catalog sending through something like:

X-Broker-API-Originating-Identity: Kubernetes \<base64 blob\>
where "\<base64 blob\>" contained a json serialisation of user.DefaultInfo
(the precise contents of the "Kubernetes" string might be up for discussion too, of course)

@pmorie

**Comment by pmorie** [comment] 2017-06-12 16:00
I'm going to try to get this implemented for 0.0.10

**Comment by duglin** [comment] 2017-07-26 14:40
While from a svc-cat perspective we don't need this for beta, which is why this is tagged as 0.2.0, it would be nice if we could get it done soon to help with the "validating-thru-impl" testing phase of the spec work.

**Comment by pmorie** [comment] 2017-07-26 15:17
At RH we view this as a must-have for beta

**Comment by pmorie** [comment] 2017-09-07 18:15
Oops, this is a dupe of #462

**Closed by pmorie** 2017-09-07 18:15 UTC
Labels: broker-api-spec-alpha
