### ISSUE TITLE
No Root Certs in Certificate Manager

### ISSUE THREAD

**Issue by richardfung** [kubernetes-incubator/service-catalog#1176] opened 2017-08-30 18:04 UTC
Right now when trying to access a broker over HTTPS, we get an error

```
      x509: failed to load system roots and no roots provided'
```

which I assume is because the certificate manager image doesn't have the ca-certificates package installed in it.

Should we be including it in the certificate manager Docker image or is there some other way we are expecting users to get root certificates onto their images?

**Comment by jmontleon** [comment] 2017-09-07 12:53
We hit this using the quay.io images with ansible-service-broker as well. Right now we're having to turn off SSL to get it to communicate.

**Comment by bmelville** [comment] 2017-09-07 15:01
What's the right way to move forward with this? Our brokers all have SSL enabled and I think it would probably be a challenge to get them disabled given our infrastructure.

Is adding the cert package to the image sufficient to resolve this problem or is there a reason it was left out?

**Comment by vaikas-google** [comment] 2017-09-07 15:41
This seems like a dupe of #606 
@pmorie did this get tackled in July?

**Comment by ash2k** [comment] 2017-10-18 00:39
@vaikas-google @pmorie this does not sound like a dupe of #606 to me. This issue is about adding standard root CAs to the docker image(s). I've just checked - there are 0 CAs installed. When I run `apt-get install ca-certificates` it installs 174.
I'd be great to get this addressed - we use Amazon Certificate Manager to get certificates for our brokers so having root CAs in the docker image is needed for secure communication.

**Closed** 2017-10-18 05:29 UTC
