### ISSUE TITLE
Set up a charts repository for easy installation

### ISSUE THREAD

**Issue by luxas** [kubernetes-incubator/service-catalog#1129] opened 2017-08-14 06:10 UTC
Would be nice with something like this:
```console
$ helm repo add service-catalog https://service-catalog.charts.k8s.io/
$ # or
$ helm repo add service-catalog https://k8s-service-catalog-charts.storage.googleapis.com/
$ helm install service-catalog/catalog
$ helm install service-catalog/ups-broker
```

and an update on every new release
cc @MHBauer @duglin

**Comment by duglin** [comment] 2017-08-14 11:48
yep - would be even nicer if we could put the ups-broker into the "catalog" chart

**Comment by MHBauer** [comment] 2017-08-14 14:03
@luxas any idea how the k8s.io domain works? How `helm repo` works for setting up a server? Any thoughts on what https://kubeapps.com/ is ? 

@duglin Isn't this just done by moving the ups chart into the catalog chart? Maybe we could symlink it?

**Comment by luxas** [comment] 2017-08-14 14:18
cc @jbeda @thockin @ixdy who knows how the `k8s.io` domain work
@MHBauer It's basically a redirect domain: https://github.com/kubernetes/k8s.io

Anyway, let's start with `https://k8s-service-catalog-charts.storage.googleapis.com/` or something like that; just a normal GCS bucket.

**Comment by arschles** [comment] 2017-08-14 23:18
This is a duplicate of https://github.com/kubernetes-incubator/service-catalog/issues/735. Referencing this issue in #735 & closing

**Closed by arschles** 2017-08-14 23:18 UTC
