### ISSUE TITLE
Binding conflict with k8s binding

### ISSUE THREAD

**Issue by mdshuai** [kubernetes-incubator/service-catalog#1031] opened 2017-07-14 05:29 UTC
After service-catalog integrate with openshift, Then get bindings, Got error:
```
# oc get bindings
Error from server (MethodNotAllowed): the server does not allow this method on the \
 requested resource
```
This is because there is a "bindings" resource in the core kubernetes API that does not support list. So I need get  by `oc get bindings.servicecatalog.k8s.io`

This two resource is totally different but same name. Need think about a better name for binding? any thought ? thanks

@liggitt @derekwaynecarr @pmorie

**Comment by pmorie** [comment] 2017-07-14 06:46
We're going to rename it; dupe of #1008, closing.

**Closed by pmorie** 2017-07-14 06:46 UTC

**Comment by liggitt** [comment] 2017-07-14 11:38
> This two resource is totally different but same name. Need think about a better name for binding?

Not necessarily. Fully qualified resource names are the future. With custom resources and add on servers, users will need to start to fully qualify their resources in scripts.

**Comment by duglin** [comment] 2017-07-14 11:57
@liggitt can you show I concrete example of this with a core type? I can't seem to get my kubectl to every allow me to use anything but the shortname for a resource type so I must be doing something wrong.

**Comment by liggitt** [comment] 2017-07-14 12:01
`kubectl get bindings.servicecatalog.k8s.io`

what version of kubectl do you have?
