### ISSUE TITLE
Add a fake for CF SB API 2.x client

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#90] opened 2016-12-01 05:42 UTC
In #86 a client was introduced for the CF SB API v2.x.  Now, we need a fake client and some tests of the existing code to exercise it.

**Comment by arschles** [comment] 2016-12-01 18:20
I'm happy to take this on after #86 is merged. Let me know if that would help @bmelville

**Comment by bmelville** [comment] 2016-12-06 17:47
@arschles feel free to take this if you like, I'll reassign.

**Comment by bmelville** [comment] 2016-12-20 17:10
@arschles if you got side tracked on this, @mkibbe1993 is ramping up on broker client stuff and could probably take over or help out.

**Comment by arschles** [comment] 2016-12-20 18:10
@bmelville that'd be great. My PR #141 was intended to build a fake in-process broker server, but that could be added later (or never) as well. @mkibbe1993 go for it!

**Comment by arschles** [comment] 2017-01-10 22:00
I've put https://github.com/kubernetes-incubator/service-catalog/pull/239 forth to build the in-memory client portion. @mkibbe1993 I think you said offline that you're pursuing #141 further?

**Comment by mkibbe1993** [comment] 2017-01-11 00:22
@arschles Yes, that's correct! Working on that now.

**Closed** 2017-01-11 19:28 UTC
Labels: broker
