### ISSUE TITLE
Make the /healthz endpoint actually check some things

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#85] opened 2016-12-01 00:35 UTC
After https://github.com/kubernetes-incubator/service-catalog/pull/84, there will be an API server running that implements a `/healthz` endpoint which simply returns a 200 OK to the client. That endpoint should do something "real" and return the actual status of the process.

**Comment by krancour** [comment] 2016-12-01 17:48
@arschles and others... any ideal what that "something 'real'" might be?

**Comment by pmorie** [comment] 2017-01-11 22:27
I think we need a healthcheck endpoint on every container process

**Comment by arschles** [comment] 2017-01-11 23:09
@krancour: following up on @pmorie's comment just now. I think "something real" will depend on which healthcheck we're talking about, since we're going to implement checks for all running processes. We'll also probably have to iterate as functionality grows.

**Comment by arschles** [comment] 2017-01-11 23:09
In the controller, for example, "something real" might mean that each control loop is responsive.

**Comment by krancour** [comment] 2017-01-12 02:26
> that each control loop is responsive

Determined how? The channels they iterate on aren't close? Might need to refactor a bit to make that happen-- not that I am opposed.

**Comment by pmorie** [comment] 2017-03-01 19:55
I'm not certain what logic this endpoint should check, @arschles @krancour do you guys have any ideas, now that we're much further down the road on this?

**Comment by pmorie** [comment] 2017-03-06 19:19
I'm moving this to MVP 2 to reduce the scope of the now-overdue MVP 1.

**Comment by arschles** [comment] 2017-03-06 19:19
The health check should check that the TPRs are all created and ready

**Comment by pmorie** [comment] 2017-03-13 17:28
Dupe of #464; closing

**Closed by pmorie** 2017-03-13 17:28 UTC
Labels: bug
