### ISSUE TITLE
Investigate Error messages during test about not being able to update status

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#1363] opened 2017-10-10 15:15 UTC
Tests are passing, but I consistently see these kinds of messages there that seem a bit troubling. Seems like either the tests are not set up right, or ?? But they add noise to the tests and it would be good to understand if they are real errors, cornercases, or whatever.

=== RUN   TestBasicFlowsSync
[restful] 2017/10/10 15:11:34 log.go:33: [restful/swagger] listing is available at https:///swaggerapi
[restful] 2017/10/10 15:11:34 log.go:33: [restful/swagger] https:///swaggerui/ is mapped to folder /swagger-ui/
**E1010 15:11:39.610161    5909 controller_instance.go:1524] ServiceInstance "test-namespace/test-instance": Failed to update status: Operation cannot be fulfilled on serviceinstances.servicecatalog.k8s.io "test-instance": the object has been modified; please apply your changes to the latest version and try again
E1010 15:11:41.032099    5909 controller_binding.go:895] Error updating status for ServiceBinding test-namespace/test-binding
E1010 15:11:46.405983    5909 controller_broker.go:727] ClusterServiceBroker "test-broker": Error updating ready condition: Operation cannot be fulfilled on clusterservicebrokers.servicecatalog.k8s.io "test-broker": StorageError: invalid object, Code: 4, Key: /ce5cb960-ed2b-4d4e-a196-50e5fec13068/clusterservicebrokers/test-broker, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 4e9a4567-adcd-11e7-a2c1-0242c0a80906, UID in object meta:** 
--- PASS: TestBasicFlowsSync (14.90s)
	framework.go:76: Starting server on port: 31375
	controller_test.go:1066: controller start
	controller_test.go:1078: informers start
	framework.go:72: Shutting down server on port: 31375
=== RUN   TestBasicFlowsAsync
[restful] 2017/10/10 15:11:53 log.go:33: [restful/swagger] listing is available at https:///swaggerapi
[restful] 2017/10/10 15:11:53 log.go:33: [restful/swagger] https:///swaggerui/ is mapped to folder /swagger-ui/
**E1010 15:11:56.265343    5909 controller_instance.go:1524] ServiceInstance "test-namespace/test-instance": Failed to update status: Operation cannot be fulfilled on serviceinstances.servicecatalog.k8s.io "test-instance": the object has been modified; please apply your changes to the latest version and try again
E1010 15:11:58.065823    5909 controller_instance.go:1524] ServiceInstance "test-namespace/test-instance": Failed to update status: Operation cannot be fulfilled on serviceinstances.servicecatalog.k8s.io "test-instance": the object has been modified; please apply your changes to the latest version and try again
E1010 15:11:59.866583    5909 controller_binding.go:895] Error updating status for ServiceBinding test-namespace/test-binding
E1010 15:12:01.069344    5909 controller_binding.go:895] Error updating status for ServiceBinding test-namespace/test-binding**
=== RUN   TestBasicFlowsWithOriginatingIdentity
[restful] 2017/10/10 15:12:26 log.go:33: [restful/swagger] listing is available at https:///swaggerapi
[restful] 2017/10/10 15:12:26 log.go:33: [restful/swagger] https:///swaggerui/ is mapped to folder /swagger-ui/
**E1010 15:12:28.782039    5909 controller_instance.go:1524] ServiceInstance "test-namespace/test-instance": Failed to update status: Operation cannot be fulfilled on serviceinstances.servicecatalog.k8s.io "test-instance": the object has been modified; please apply your changes to the latest version and try again**
--- PASS: TestBasicFlowsWithOriginatingIdentity (5.33s)
	framework.go:76: Starting server on port: 26481
	controller_test.go:1066: controller start
	controller_test.go:1078: informers start
	framework.go:72: Shutting down server on port: 26481

**Comment by pmorie** [comment] 2017-10-10 15:31
I think what we're seeing is races between the work queue in the controller and the informer cache used by the lister not being updated

**Comment by staebler** [comment] 2017-10-26 02:56
@pmorie You are spot on with what the underlying cause of those errors are. They come as a result of updating the status multiple times during a single reconciliation loop. When the reconciliation loop ends, the next reconciliation loop may try to reconcile the resource in its state from the first status update. This reconciliation then fails because the resource being used is out-of-date.

**Comment by luksa** [comment] 2018-03-12 15:10
Most of these are now fixed by #1779 and #1819, but the integration tests still print out this error in a few places. The cause of those is legit: the test is deleting the resource in the middle of a reconciliation loop iteration:
```
I0312 14:21:09.142127    4982 controller_binding.go:192] ServiceBinding "test-namespace/test-binding": Processing
I0312 14:21:09.142147    4982 controller_binding.go:538] ServiceBinding "test-namespace/test-binding": References a non-existent ServiceInstance "test-namespace/nothereinstance"
I0312 14:21:09.142157    4982 controller_binding.go:588] ServiceBinding "test-namespace/test-binding": Updating status
I0312 14:21:09.340507    4982 request.go:480] Throttling request took 398.676693ms, request: DELETE:https://localhost:13299/apis/servicecatalog.k8s.io/v1beta1/namespaces/test-namespace/servicebindings/test-binding
I0312 14:21:09.348214    4982 wrap.go:42] DELETE /apis/servicecatalog.k8s.io/v1beta1/namespaces/test-namespace/servicebindings/test-binding: (7.459368ms) 200 [[___TestCreateServiceBindingInvalidInstance_in_github_com_kubernetes_incubator_service_catalog_test_integration/v0.0.0 (linux/amd64) kubernetes/$Format] [::1]:42182]
I0312 14:21:09.540506    4982 request.go:480] Throttling request took 398.27679ms, request: PUT:https://localhost:13299/apis/servicecatalog.k8s.io/v1beta1/namespaces/test-namespace/servicebindings/test-binding/status
I0312 14:21:09.541676    4982 wrap.go:42] PUT /apis/servicecatalog.k8s.io/v1beta1/namespaces/test-namespace/servicebindings/test-binding/status: (901.963µs) 409 [[___TestCreateServiceBindingInvalidInstance_in_github_com_kubernetes_incubator_service_catalog_test_integration/v0.0.0 (linux/amd64) kubernetes/$Format] [::1]:42182]
E0312 14:21:09.541945    4982 controller_binding.go:591] ServiceBinding "test-namespace/test-binding": Error updating status: Operation cannot be fulfilled on servicebindings.servicecatalog.k8s.io "test-binding": the object has been modified; please apply your changes to the latest version and try again
```

These log statements are logged when there is a problem with the instance/binding (such as pointing to a nonexistent broker/instance). The controller initially re-tries this multiple times per second and posts a new status every time, even though the status is exactly the same as the current status. Do we want to check this before posting a status (non)update?  Looks like the API server doesn't increase the resource version if you post a status update that doesn't actually change the status. 

And one more things: the log statement `the object has been modified; please apply your changes to the latest version and try again` should probably be logged as INFO instead of ERROR, because it's a fairly normal event (it occurs every time someone updates/deletes the resource while the controller is in the middle of processing the resource). We probably want to use the ERROR level for actual errors, right?

**Comment by liggitt** [comment] 2018-03-12 15:13
> The controller initially re-tries this multiple times per second and posts a new status every time, even though the status is exactly the same as the current status. Do we want to check this before posting a status (non)update?

Yes, the controller should avoid sending no-op updates

> Looks like the API server doesn't even increase the resource version if you post a status update that doesn't actually change the status.

Correct, that is working as designed

**Comment by MHBauer** [comment] 2018-06-08 20:06
seems fixed
/close

**Closed by MHBauer** 2018-06-08 20:06 UTC
