### ISSUE TITLE
Add support for re-GETting the catalog from a broker

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#812] opened 2017-05-09 18:26 UTC
Umbrella issue to track adding support for this. Things to consider:
- manually request from a kube admin to re-get
- periodic re-get
- ability to ask for certain brokers to be excluded from the auto-re-get
- do the re-get and reconcile the data

**Comment by pmorie** [comment] 2017-05-12 22:37
Dupe of https://github.com/kubernetes-incubator/service-catalog/issues/705; closing

**Closed by pmorie** 2017-05-12 22:37 UTC
Labels: broker-api-spec-compliance
