### ISSUE TITLE
Containerized dependency resolution doesn't quite work

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#217] opened 2017-01-04 16:28 UTC
The following fails:

```
$ DOCKER=1 make clean build
```

The problem seems to be related to the use of glide within the container, so to narrow the scope of the issue, consider the following command instead:

```
$ DOCKER=1 make clean .init
```

Yields:

```
rm -rf bin
rm -f .init .scBuildImage .generate_files .generate_exes
rm -f /Users/kent/Code/go/src/github.com/kubernetes-incubator/service-catalog/coverage.html
find cmd contrib pkg util -name zz_generated* -exec rm {} \;
docker rmi -f scbuildimage > /dev/null 2>&1 || true
sed "s/GO_VERSION/1.7.3/g" < hack/Dockerfile | \
	  docker build -t scbuildimage \
	    --build-arg UID=503 \
	    --build-arg GID=20 \
	    --build-arg USER=kent \
	    -
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM golang:1.7.3
 ---> ef15416724f6
Step 2 : ARG UID=0
 ---> Running in 58563bdb54a6
 ---> d146b3ad237f
Removing intermediate container 58563bdb54a6
Step 3 : ARG GID=0
 ---> Running in 4cdd19bcd43c
 ---> 32331d6ea311
Removing intermediate container 4cdd19bcd43c
Step 4 : ARG USER=root
 ---> Running in e80accb5d306
 ---> 529cc1dbad35
Removing intermediate container e80accb5d306
Step 5 : ENV GLIDE_VERSION v0.12.3
 ---> Running in 4ea3ce0e174d
 ---> 3e1a4e31b02f
Removing intermediate container 4ea3ce0e174d
Step 6 : RUN curl -sSL https://github.com/Masterminds/glide/releases/download/$GLIDE_VERSION/glide-$GLIDE_VERSION-linux-amd64.tar.gz     | tar -vxz -C /usr/local/bin --strip=1
 ---> Running in 60b1f3957c97
linux-amd64/glide
linux-amd64/LICENSE
linux-amd64/README.md
 ---> 3dfb2ffb0841
Removing intermediate container 60b1f3957c97
Step 7 : RUN groupadd -g $GID mygroup || true
 ---> Running in 862f43e2107d
groupadd: GID '20' already exists
 ---> 85cbe0b9d6af
Removing intermediate container 862f43e2107d
Step 8 : RUN useradd -u $UID -g $GID $USER || true
 ---> Running in c428eb50f30e
 ---> 6adcf39aefac
Removing intermediate container c428eb50f30e
Step 9 : USER $USER
 ---> Running in fb604a159185
 ---> 8885b47e566b
Removing intermediate container fb604a159185
Step 10 : RUN go get -u github.com/golang/lint/golint
 ---> Running in 25af7aed9115

 ---> f6336dbb970b
Removing intermediate container 25af7aed9115
Step 11 : RUN mkdir -p /go/src/github.com/kubernetes-incubator/service-catalog
 ---> Running in 16d712c28f23
 ---> 976b2b340ef2
Removing intermediate container 16d712c28f23
Step 12 : WORKDIR /go/src/github.com/kubernetes-incubator/service-catalog
 ---> Running in 7cece8b2e5b3
 ---> 411803f809f2
Removing intermediate container 7cece8b2e5b3
Successfully built 411803f809f2
touch .scBuildImage
docker run --rm -ti -v /Users/kent/Code/go/src/github.com/kubernetes-incubator/service-catalog:/go/src/github.com/kubernetes-incubator/service-catalog -e GOOS=$SC_GOOS -e GOARCH=$SC_GOARCH scbuildimage glide install --strip-vendor

[INFO]	Downloading dependencies. Please wait...
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x8066a0, 0xc420012090)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction.func1(0xc4200e3788)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:472 +0x29e
panic(0x8066a0, 0xc420012090)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs.NewHgRepo(0xc420377770, 0x22, 0xc42041fdc0, 0x69, 0xc420377701, 0x22, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs/hg.go:47 +0x513
github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs.NewRepo(0xc420377770, 0x22, 0xc42041fdc0, 0x69, 0xa7c8e0, 0xc420377700, 0x22, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs/repo.go:163 +0x20d
github.com/Masterminds/glide/cfg.(*Dependency).GetRepo(0xc4203135e0, 0xc42041fdc0, 0x69, 0xc42041fdc0, 0x69, 0x0, 0x22)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/cfg/config.go:527 +0x62b
github.com/Masterminds/glide/repo.LazyConcurrentUpdate(0xc42013fc00, 0x3e, 0x40, 0xc42017cf40, 0xc4201e2480, 0x0, 0x40)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/repo/installer.go:449 +0x2c2
github.com/Masterminds/glide/repo.(*Installer).Install(0xc42017cf40, 0xc420228540, 0xc4200ecb40, 0x40, 0x1, 0x4)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/repo/installer.go:98 +0x5d5
github.com/Masterminds/glide/action.Install(0xc42017cf40, 0x86ef01)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/action/install.go:43 +0x1a8
main.commands.func12(0xc42018c280, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:515 +0x338
reflect.Value.call(0x7f4ba0, 0x8acd00, 0x13, 0x86b617, 0x4, 0xc4200e3728, 0x1, 0x1, 0x4933e8, 0x860640, ...)
	/usr/local/Cellar/go/1.7.1/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x7f4ba0, 0x8acd00, 0x13, 0xc4200e3728, 0x1, 0x1, 0x4b, 0x140, 0x140)
	/usr/local/Cellar/go/1.7.1/libexec/src/reflect/value.go:302 +0xa4
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction(0x7f4ba0, 0x8acd00, 0xc42018c280, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:481 +0x1e0
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x86cb40, 0x7, 0x86adca, 0x1, 0x0, 0x0, 0x0, 0x878877, 0x20, 0x0, ...)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:186 +0xc26
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc42017a000, 0xc42000a0c0, 0x3, 0x3, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:235 +0x60c
main.main()
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:109 +0x637
make: *** [.init] Error 2
```

fwiw, I am quite certain this is a permission issue. See thread below (ironically opened by yours truly over a year ago):

https://github.com/Masterminds/glide/issues/149

cc @duglin

**Comment by duglin** [comment] 2017-01-04 16:49
just FYI - I don't see this but I bet its because I never run glide from outside of a container.
Try erasing your vendor dir and try it again (or maybe your .glide files/dirs in the root of the repo).
This is related to an issue I'm planning on opening related to what "clean" should actually remove.

**Comment by duglin** [comment] 2017-01-04 17:06
actually, are you running with master? I'm wondering if the latest Dockerfile changes (that run things as a non-root user) help with this

**Comment by krancour** [comment] 2017-01-04 18:00
Yes. I am running this from master. Good thought on the ownership dispute resulting from vendored stuff that was put there whilst running (previously) out-of-container. So I deleted it, but that just leads to a different permissions problem:

```
$ DOCKER=1 make clean .init
rm -rf bin
rm -f .init .scBuildImage .generate_files .generate_exes
rm -f /Users/kent/Code/go/src/github.com/kubernetes-incubator/service-catalog/coverage.html
find cmd contrib pkg util -name zz_generated* -exec rm {} \;
docker rmi -f scbuildimage > /dev/null 2>&1 || true
sed "s/GO_VERSION/1.7.3/g" < hack/Dockerfile | \
	  docker build -t scbuildimage \
	    --build-arg UID=503 \
	    --build-arg GID=20 \
	    --build-arg USER=kent \
	    -
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM golang:1.7.3
 ---> ef15416724f6
Step 2 : ARG UID=0
 ---> Running in 480ced0c5b4a
 ---> 1f5752078b67
Removing intermediate container 480ced0c5b4a
Step 3 : ARG GID=0
 ---> Running in 70b550209307
 ---> 3b6a10f22657
Removing intermediate container 70b550209307
Step 4 : ARG USER=root
 ---> Running in 22b2ab7d0173
 ---> 222fcb2130c3
Removing intermediate container 22b2ab7d0173
Step 5 : ENV GLIDE_VERSION v0.12.3
 ---> Running in 2a2d68f8989d
 ---> 4412edf7d35d
Removing intermediate container 2a2d68f8989d
Step 6 : RUN curl -sSL https://github.com/Masterminds/glide/releases/download/$GLIDE_VERSION/glide-$GLIDE_VERSION-linux-amd64.tar.gz     | tar -vxz -C /usr/local/bin --strip=1
 ---> Running in 636288b9d0c8
linux-amd64/glide
linux-amd64/LICENSE
linux-amd64/README.md
 ---> 62dba61b7bef
Removing intermediate container 636288b9d0c8
Step 7 : RUN groupadd -g $GID mygroup || true
 ---> Running in 9db9d4bb4a6d
groupadd: GID '20' already exists
 ---> 30c266e8cac6
Removing intermediate container 9db9d4bb4a6d
Step 8 : RUN useradd -u $UID -g $GID $USER || true
 ---> Running in 0e3831b3e8a6
 ---> 40539a597443
Removing intermediate container 0e3831b3e8a6
Step 9 : USER $USER
 ---> Running in b13d7ad833f5
 ---> 162040ff8791
Removing intermediate container b13d7ad833f5
Step 10 : RUN go get -u github.com/golang/lint/golint
 ---> Running in a186692a86fe
 ---> 335bd0ab48f6
Removing intermediate container a186692a86fe
Step 11 : RUN mkdir -p /go/src/github.com/kubernetes-incubator/service-catalog
 ---> Running in 5e24ece31e9e
 ---> c0551d3b2a17
Removing intermediate container 5e24ece31e9e
Step 12 : WORKDIR /go/src/github.com/kubernetes-incubator/service-catalog
 ---> Running in c354c0f96986
 ---> 847cd344913e
Removing intermediate container c354c0f96986
Successfully built 847cd344913e
touch .scBuildImage
docker run --rm -ti -v /Users/kent/Code/go/src/github.com/kubernetes-incubator/service-catalog:/go/src/github.com/kubernetes-incubator/service-catalog -e GOOS=$SC_GOOS -e GOARCH=$SC_GOARCH scbuildimage glide install --strip-vendor
[ERROR]	Could not create vendor: mkdir vendor: permission denied
make: *** [.init] Error 1
```

Is it possible the stuff you did re: running as non-root user isn't fully vetted on MacOS / Docker Machine?

**Comment by duglin** [comment] 2017-01-04 18:12
ok run exclusively from a ubuntu VM - and it works both as root and non-root user.
I don't have Docker installed on my mac and I bet its the -v that's messing with things.
Can you try?  `docker run --rm -ti -v /Users/kent/Code/go/src/github.com/kubernetes-incubator/service-catalog:/go/src/github.com/kubernetes-incubator/service-catalog ls -la`

**Comment by duglin** [comment] 2017-01-04 18:21
Even though I can't completely reproduce your end, what's interesting is that when I run that docker command (with the cli on my mac and the daemon running in a ubuntu vm), the -v has no real impact because it can't mount across hosts.  But, it also doesn't give me an error msg - which is kind of interesting.

BUT, and here's the kicker... the current dir isn't owned by me, its owned by root. W/o the -v its owned by me.  I suspect this might all be related to how docker is mounting the dir. So I'm really curious now to see who owns your '.' dir.

**Comment by duglin** [comment] 2017-01-04 18:45
Morgan just tried this, using the Docker for Mac stuff, and it seemed to work. @krancour where is your docker daemon running?

**Comment by krancour** [comment] 2017-01-04 19:38
My Docker daemon is running on Docker Machine.

**Comment by krancour** [comment] 2017-01-04 19:49
@duglin 

```
$ docker run --rm -ti -v /Users/kent/Code/go/src/github.com/kubernetes-incubator/service-catalog:/go/src/github.com/kubernetes-incubator/service-catalog scbuildimage ls -la
total 92
drwxr-xr-x 1 1000 staff     918 Jan  4 19:45 .
drwxr-xr-x 3 kent dialout  4096 Jan  4 19:45 ..
drwxr-xr-x 1 1000 staff     544 Jan  4 19:45 .git
-rw-r--r-- 1 1000 staff     142 Dec 28 22:30 .gitignore
drwxr-xr-x 1 1000 staff     102 Dec 27 21:19 .glide
-rw-r--r-- 1 1000 staff       0 Jan  4 19:45 .scBuildImage
-rw-r--r-- 1 1000 staff     493 Dec 27 15:25 .travis.yml
-rw-r--r-- 1 1000 staff    1709 Dec 16 22:02 CONTRIBUTING.md
-rw-r--r-- 1 1000 staff    3223 Dec 16 22:02 Jenkinsfile
-rw-r--r-- 1 1000 staff   11357 Nov 28 18:12 LICENSE
-rw-r--r-- 1 1000 staff    9342 Jan  4 19:45 Makefile
-rw-r--r-- 1 1000 staff      99 Jan  3 22:08 OWNERS
-rw-r--r-- 1 1000 staff    1938 Jan  4 15:30 README.md
-rw-r--r-- 1 1000 staff    1366 Dec 16 22:02 REVIEWING.md
drwxr-xr-x 1 1000 staff     136 Jan  4 19:45 cmd
-rw-r--r-- 1 1000 staff    3061 Dec 16 22:02 code-of-conduct.md
drwxr-xr-x 1 1000 staff     170 Jan  4 19:45 contrib
drwxr-xr-x 1 1000 staff     102 Dec 12 17:04 deploy
drwxr-xr-x 1 1000 staff     238 Jan  4 15:30 docs
-rw-r--r-- 1 1000 staff   19059 Jan  4 15:30 glide.lock
-rw-r--r-- 1 1000 staff     907 Jan  4 15:30 glide.yaml
drwxr-xr-x 1 1000 staff     646 Jan  4 19:45 hack
drwxr-xr-x 1 1000 staff     136 Jan  4 19:45 model
drwxr-xr-x 1 1000 staff     272 Jan  4 19:45 pkg
-rwxr-xr-x 1 1000 staff     709 Dec 12 17:04 run.sh
-rw-r--r-- 1 1000 staff    2919 Dec 16 22:02 terminology.md
drwxr-xr-x 1 1000 staff     102 Jan  4 19:45 util
```

**Comment by krancour** [comment] 2017-01-04 19:52
`1000` and `staff` are the `gid` and primary group, respectively, for the `docker` user in my Docker Machine... I get what's going on here...

**Comment by krancour** [comment] 2017-01-04 19:55
The user I am running as inside the container is modeled after the user I run as on my Mac...

But (in case you don't know how Docker Machine handles volume mounting), a user's entire home directory gets mounted to the Docker Machine VM, which then allows `-v` to work because at that point, you're not mounting across hosts (which you've noted cannot be done).

So from the VM's point of view, that user isn't the owner of the files.

**Comment by krancour** [comment] 2017-01-04 20:25
@duglin curious... why are we going so far out of our way to not run the build as root when running it in a container?

In principle, I am a strong adherent of _not_ running processes in containers as root since containers share the host's kernel...

But I'm not sure why we'd be observing that so strictly in a container that's used only for building-- it's essentially throwaway and won't ever run in production.

**Comment by duglin** [comment] 2017-01-04 20:48
@krancour we used to run it all as root but then we ran into a problem where the resulting files could not be accessible by the outside user -see: https://github.com/kubernetes-incubator/service-catalog/pull/208#issuecomment-269710622

Now its very possible that I went overboard and a better solution might have been to simply do a `chmod go=u` on everything during the build.  Thoughts?

**Comment by pmorie** [comment] 2017-01-11 22:52
Fixed in master; closing

**Closed by pmorie** 2017-01-11 22:52 UTC
